services:
  jekyll:
    build: .
    ports:
      - "4000:4000"
      - "35729:35729"  # LiveReload 포트
    volumes:
      - .:/site:Z
      - bundle_cache:/usr/local/bundle:Z
    environment:
      - JEKYLL_ENV=development
    command: bundle exec jekyll serve --host 0.0.0.0 --livereload --force_polling
    security_opt:
      - label=disable  # SELinux 호환성

volumes:
  bundle_cache:
